### PR TITLE
Feature/78, 79, etc. Vignettes translated to R Markdown

### LINKED ISSUE #78: Feature request: online documentation with pkgdown or similar
Package [**pkgdown**](http://pkgdown.r-lib.org/) enables the possibility to create a website with online documentation. [GitHub Pages](https://pages.github.com/) can be used to host the website.

I would be really convenient if `hyperSpec` had this kind of feature thus I suggest creating it.

### LINKED ISSUE #79: Translate vignettes from `Sweave` to `R Markdown`
Vignettes are in LaTeX/Sweave, and should be translated into markdown and building by `knitr`.

- branch `knitr-vignettes` already exists. 

- [x] flu
- [x] laser
- [x] baseline  
- [x] chondro  
- [x] hyperspec
- [x] plotting
- [x] fileio
  - [x] untangle historic mix with unit tests into vignette and unit tests

### LINKED ISSUE #135: Move vignette *hyperSpec*
... so that its primary directory is the package vignette folder. 

see #132 

This is mostly a matter of `git` and the `Makefile`s.

### LINKED ISSUE #136: Move vignette *plotting*
... so that its primary directory is the package vignette folder.

see #132

This is mostly a matter of git and the Makefiles.

### PR DESCRIPTION
**Pull request by GegznaV**
I opened this PR (pull request) for the discussions related to translation and modification of vignettes. It continues (or complements) the discussions in #94, #93, #79, #135, #138, #139 and possibly in #27, #71 and #119.

In this PR:

- [x] GitHub Actions are set to build **`pkgdown`** website automatically (closes #78).
- [x] Vignettes are translated to Rmd (closes #79).
- [x] Vignettes are moved to the package's `vignettes` folder (closes #135, closes #136). 
- [x] Datasets are converted to "static" versions (#137).
- [x] Code to create "static" versions of package data is created in directory `data-raw` (#137).

***
For those who are going to work on R Markdown vignettes, I suggest doing 2 things:

1) Write a **message** in this issue when you **start** (and finish) working on some vignettes and state the **name** of that vignette. I think if several people make changes to the same vignette, it might be difficult to merge changes (and it would be unnecessary work).
2) **Follow the vignette style rules** described in #93 (of course, we may discuss and create new rules, if these seem to be unreasonable).

### CODE REVIEW

**Comment by GegznaV** [comment]
I'm still working on `fileio` and `baseline` vignettes. 

Others may are ready to be review and modified by other contributors (@bryanhanson).

**Comment by bryanhanson** [comment]
Perhaps not necessary, but couldn't we branch off of this branch (`feature/vignettes-in-rmd`), creating one additional branch for each vignette as it is reviewed?  Maybe that's getting too many layers deep.

**Comment by GegznaV** [comment]
Usually, a person, who wants to modify one or several vignettes, creates a
fork and wors on his/her fork. When the work is completed, the changes are
merged into this branch.

I also think, that some information should not repeat in several vignettes
(it would be easier to keep the documentation up to date if there were only
references in one place and the information in the other one) and some
vignettes (e.g., hyperSpec) should be split into several separate documents.

Because of these reasons, I do not think that separate branches are
necessary.

2020 birž. 4, kt 22:53, Bryan Hanson <notifications@github.com> rašė:

**Comment by bryanhanson** [comment]
Got it!  Thanks.

**Comment by bryanhanson** [comment]
I am starting work on the intro vignette, `hyperSpec.Rmd`.

**Comment by bryanhanson** [comment]
I am done with `hyperSpec.Rmd` for now.  I committed my changes a few minutes ago and they are listed just above under Claudia's name!  I guess this branch has a `gitconfig` specifying that I am Claudia, which I will fix.  These changes represent a significant re-organization of this document.  It still needs a lot of work; there are whole sections that I have not touched.  At this time I'm going to ask everyone to take a look at the organizational aspects, not the details which will probably change further.  If these global changes are acceptable then I'll pick up where I left off and continue working.  Otherwise, we'll discard it all.   I'm going to mention over on Slack and provide the `html` for your easy inspection.

**Comment by bryanhanson** [comment]
@GegznaV in particular and others.  I am starting again on revisions to `hyperSpec.Rmd`.  I will pull and push often so if you need to make changes for automatic builds we should be OK.  I am directly running `render("hyperSpec.Rmd")` to test how the file is processing -- I'm not using `make` or any other approach.

**Comment by GegznaV** [comment]
I hope nobody is working on the vignettes as I'm going to create commits to all of them.

**Comment by bryanhanson** [comment]
I have the intro vig “checked out” per the messages system you set up but you have all my commits currently.

**Comment by GegznaV** [comment]
I still continue the work on vignettes...

**Comment by GegznaV** [comment]
I'm still working on the vignettes...

**Comment by GegznaV** [comment]
I finished for today.

**Comment by GegznaV** [comment]
For those, who review vignettes: if you want to insert commets, I recommend using the following template block:

    
    ```{block, type="note-t", echo=show_reviewers_notes}
    **Reviewer's notes**:
    
    1. `# FIXME:`{.r} ...
    2. `# TODO:`{.r} ...
    3. `# NOTE:`{.r} ...
    ```
    

Instead of the word `Reviewer's`, write your name, e.g., `V. Gegzna's`.

Use `FIXME` if something should be fixed, `TODO` if something should be implemented and `NOTE` for other notes.

Due to option `type="note-t"`, the comments could be clearly visible in rendered documentation. If syntax \` # FIXME: \`{.r} is used, as in R code words `# FIXME` and ` # TODO` are also highlighted in a different color. 

Due to option `echo=show_reviewers_notes`, these comments can be easily hidden from the end-user.

**Comment by GegznaV** [comment]
The _primary goal_ of this PR was to **translate** the vignettes from Rnw **to Rmd**. I think, that this goal is achieved and PR is ready ✔️ to be merged. There are some of my and Bryan's notes in the Rmd files but they are hidden in the rendered documents.

If @cbeleites, @bryanhanson, @ximeg, or @eoduniyi  think that there are any Rnw to Rmd translation errors (e.g., broken links are the most common ones), I will fix them. And the other issues (related to the contents, grammar, polishing the vignettes, reorganizing the materials, fixing other errors) are not directly related to Rnw → Rmd translation and should be fixed **on a separate branch** after this branch `feature/vignettes-in-rmd` is merged.

This PR has some features (e.g., enabled `pkgdown` website building) that are required on the `develop` branch to solve other documentation related issues. (This is one more reason why I think it is time to merge it.)

P.S. @bryanhanson wrote that he is going to work on reviewing/polishing `hyperSpec.Rmd` vignette on the weekend. I think it's ok to have some more commits in this branch. But next week I expect it would be merged into `develop`.

**Comment by GegznaV** [comment]
The rendered versions of the vignettes on this branch can be found here (on `dev` version of `pkgdown`):
http://cbeleites.github.io/hyperSpec/dev/articles/index.html

**Comment by GegznaV** [comment]
The hyperSpec vignette is present in `pkgdown` website and could be found here: cbeleites.github.io/hyperSpec/dev/articles/hyperspec.html Unfortunately, the vignette is not auto-linked correctly in `pkgdown` due to capital letters in its name. 

See also https://github.com/cbeleites/hyperSpec/issues/168#issuecomment-646985318

**Comment by bryanhanson** [comment]
I am done with `hyperSpec.Rmd` for the time being, so we can move forward with this now, and then create new branches, e.g. `feature/intro-vig` to work on the individual vignettes in the future.  Vilmantas is probably the only one who sees the big picture of this pull request so I think it is best if he merges it.  From my perspective, everything works well with the intro vignette which means the infrastructure Vilmantas created is working.  So I'm in favor of merging ASAP.

**Comment by cbeleites** [comment]
For those wondering: the breaking change are the additional github CI actions that check the package for various operating systems.

**Pull request merged**
