### PR TITLE
Clean depracated functions and unit tests

### LINKED ISSUE #326: Functions moved to hySpc.read.jdx
We write new functions for hySpc.read.jdx so there isn't any function moving from hyperSpec to the new package. But the old functions for read jdx file are still needed to be deprecated in hyperSpec.

### PR DESCRIPTION
**Pull request by GegznaV**
I create this PR of the @cbeleites branch so that we could discuss the changes made.

Closes #326
Related to #330,  r-hyperspec/r-hyperspec.github.io#17

In addition to updates by @cbeleites, I:

- fixed some lines of code to pass R CMD check,
- updated several more unit tests to avoid warnings due to deprecation messages,
- updated the style in some functions (did it here as I wanted to avoid conflicts with other PRs by me).

### CODE REVIEW

**Comment by GegznaV** [comment]
I added some commits to this PR that are related to #330 (style of function description titles).

**Comment by GegznaV** [comment]
After updates in unit tests, there are no warnings related to the function deprecation:
image

So I think this PR is ready to be merged. And if some new improvements are needed, they can be added as a new PR.
What do you think @cbeleites?

**Review by cbeleites — APPROVED** [review]
This is an intermediate stage of deprecating lots of functions, a) to rename or b) to move them into separate packages. Work is not complete, but it's time to merge this into develop to avoid parallel development.

**Comment by GegznaV** [comment]
Thanks for merging, @cbeleites

**Pull request merged**
