### PR TITLE
Translate vignettes

### PR DESCRIPTION
**Pull request by GegznaV**
I created this pull request so that @cbeleites could review the vignettes, that are translated to Rmd. Vignettes that are ready to be reviewed:

- hyperspec
- plotting

You should build these files into HTML as you do with regular Rmd files (I use the "knit" button in RStudio).

Others are not properly translated as only automatic script converted some parts to Rmd. So please, do not merge the pull request yet. I will finish translating the remaining vignettes sometime in the future and will announce about that.

The main principles I used for the translation are described in #93.

Related: #93, #79

### CODE REVIEW

**Comment by cbeleites** [comment]
I'll try to have a look next week. 

Many thanks for your efforts. I do know how much work that translation is, and I highly appreciate it!

**Comment by ximeg** [comment]
Hi @GegznaV , GitHub allows you to change the type of this pull request to be 'draft'. This way you indicate that it is still work in progress and it cannot be merged until you mark it yourself as completed.

**Comment by GegznaV** [comment]
Three translated vignettes (`hyperspec`, `plotting`, and `chondro`) are ready to be reviewed. The HTML versions are here:

- [hyperspec.zip](https://github.com/cbeleites/hyperSpec/files/4658695/hyperspec.zip)
- [plotting.zip](https://github.com/cbeleites/hyperSpec/files/4658697/plotting.zip)
- [chondro.zip](https://github.com/cbeleites/hyperSpec/files/4658694/chondro.zip)

And you may fork my branch to explore the source code. At this phase, I tried not to change the contents as much as possible. And before going to the translation of the next vignette I would like to know if you have any remarks that would help me. Or is it OK for you how it looks now?

In the places that, in my opinion, need attention, I added "Translator's notes" like this one:
image
Some of these remarks are related to the contents and should be addressed later (when the translation is finished).

I demonstrated, that it is possible to do multi-subplot pots like this one:
image
And yes, sometimes these plots look blurry as they are bigger than the width of the text so they are forced to fit.

But I think that it is more convenient to create plots without subplots as the code, which generates the plot, is always above the plot:
image


What is your opinion on this issue?

**Comment by GegznaV** [comment]
By saying:

>  Or is it OK for you how it looks now?

I meant if you'd accept the vignettes as they look now. (Someone else could continue on polishing other aspects of these documents then).

**Comment by ximeg** [comment]
Hi @GegznaV 
Awesome, many thanks for your great contribution, it looks gorgeous! :+1: 

1) Regarding separate plots or multi-subplots: I would prefer to usually have separate plots - they are easier to maintain and they better correspond to the code. However, in the specific case you asking about, we compare 3 plots with each other, and in such a case side by side makes more sense.

2) I found minor issues in the Rmd files, and instead of writing a bunch of comments here, I'll post several small pull requests to your repo, for example [this one for chondro.Rmd](https://github.com/GegznaV/hyperSpec/pull/1)

3) To reproduce the vignettes, packages `bookdown`, `ggplotify` and `ggpubr` are necessary. They are not installed with hyperSpec by default. We need some solution for that. May be it makes sense to include them temporarily?? @cbeleites - do you have an opinion on that?

**Comment by GegznaV** [comment]
After today's changes related to changed branches, I can no longer pull changes into my branch `translate_vignettes`. I even cannot checkout to that branch with the following message:

image

Any suggestions?

**Comment by ximeg** [comment]
@GegznaV We run against the github [git lfs download bandwidth quota limit](https://help.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota) (which we didn't even know exists).

Turns out, that the quota is per-user basis (in this case @cbeleites ), and it applies to all repositories of this user, **and to all forks of this repository**. The bandwidth quota is consumed everytime **anyone** downloads file from git LFS.

In the future we get rid of git LFS in this repo. For now, I purchased a gift card and sent to Claudia, so that she can [get more data](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/viewing-your-git-large-file-storage-usage) and we can continue working.

**Comment by GegznaV** [comment]
Temporary preview of the **hyperSpec**'s vignettes in a form of *GitBook* book (built with **bookdown**) are available at https://hyperspec-book.netlify.app/. The preview will be updated as I progress with the translation.

**Comment by ximeg** [comment]
@GegznaV This is very cool! We appreciate your efforts so much!

**Comment by bryanhanson** [comment]
Yes, I concur with @ximeg this is a very big step forward and much appreciation to Vilmantas!  What is the short-term plan for these?  Will we hold off on polishing these until most of the other work planned for the summer is done?  Some of these will change a lot I suppose, some only a little.  Perhaps the introduction will change little and can be reviewed now?  What do you think @cbeleites ?  I'm glad to review these but don't want to if many changes are coming.

**Comment by GegznaV** [comment]
I almost finished translating into Rmd. Now I'm working on `fileio` ( the last vignette) and I hope to finish before the end of the next week. If you want to preview the translations there are two options (they use different CSS files so the appearance may differ in some places):

1) Preview in the form of a GitBook:
https://hyperspec-book.netlify.app/

1) Preview in the form of a HTML vignettes:
https://hyperspec-book.netlify.app/vignettes/hyperspec.html
https://hyperspec-book.netlify.app/vignettes/fileio.html
https://hyperspec-book.netlify.app/vignettes/plotting.html
https://hyperspec-book.netlify.app/vignettes/baseline.html
https://hyperspec-book.netlify.app/vignettes/chondro.html
https://hyperspec-book.netlify.app/vignettes/flu.html
https://hyperspec-book.netlify.app/vignettes/laser.Rmd

**Comment by cbeleites** [comment]
@bryanhanson , with the exception of vignettes fileio and chondro, the others (hyperSpec, laser, flu) should be fine to review now.

**Comment by bryanhanson** [comment]
@cbeleites I would be glad to do so.  I do tend to do a lot of polishing of such documents (I'm a perfectionist and have made documents for students for decades).  Is that OK?  Or would you prefer a much lighter touch?

@GegznaV just to confirm, these changes are on https://github.com/GegznaV/hyperSpec/tree/translate_vignettes ? So I will fork your fork and when done do a pull request to your repo, and eventually you will do a pull request back into the main `hyperSpec` on some branch?

**Comment by ximeg** [comment]
@bryanhanson Yes, this is how I did it - fork of a fork :) It worked.

**Comment by GegznaV** [comment]
> just to confirm, these changes are on https://github.com/GegznaV/hyperSpec/tree/translate_vignettes ?

 @bryanhanson I created a new feature branch  [`feature/vignettes-in-rmd`](https://github.com/cbeleites/hyperSpec/tree/feature/vignettes-in-rmd) and committed all my changes to that branch. You may fork that branch and commit your corrections to it. It would be easier to use a branch than fork.

**Pull request merged**
