### PR TITLE
Bugfix/132 delete makefiles

### LINKED ISSUE #132: Get (mostly) rid of `make`
**hyperSpec** currently has a very elaborate `Makefile` system. This proved to be difficult for contributors. 

One goal of the refactoring during Google Summer of Code 2020 is to arrive at a state where `Makefile`s are not or at least only hardly needed.

Changes/proposals should thus aim at reducing the complexity of the `Makefiles`.

### PR DESCRIPTION
**Pull request by ximeg**
Resolves #132

I was able to successfully build and check hyperSpec using only devtools in RStudio after I deleted all remaining Makefiles.

### CODE REVIEW

**Comment by GegznaV** [comment]
As `hyperSsec` package has irregular structure of directories, `pkgdown` does not recognize `README.md`. Thus this `index.md` file (displayed as pkgdown website home page) https://github.com/cbeleites/hyperSpec/blob/develop/hyperSpec/pkgdown/index.md
should contain the same information as `README.md`. 

@ximeg Could you update `index.md` too?

**Comment by ximeg** [comment]
@GegznaV I did that. However, if both files should have the same content, does it make sense to replace `index.md` with a symlink to `README.md`?

**Comment by GegznaV** [comment]
I don't know what symbolic links are and how they work. But I think that the same information should not be pasted as this is error-prone.

 I was thinking of creating `README.Rmd` (instead `.md`), which could be rendered by Git Hub actions into both `README.md` and `index.md`. (in this way we can have, e.g.,  a date in the documentation to know when it was created).

In other packages with regular directory structure **pkgdown** uses `README.md` and `index.md` is rarely needed.

**Comment by ximeg** [comment]
Apparently [symbolic links do not work properly on Windows and need workarounds](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows), so generally it's better to avoid them. On the other hand, `index.md` is needed only for github pages, where it most probably would work even if it is a symlink. We may try to do that and see what happens. If it leads to issues, the commit can be reverted.

@GegznaV I like this idea of having single Rmd file that gets rendered in README.md and index.md, but it would require some work to do.

**Comment by ximeg** [comment]
Sorry for the mess. I intended to use git flow to merge this PR into develop, but forgot to fetch the most recent develop state... Technically this PR is merged, although indirectly.

**Pull request closed without merging**
