### PR TITLE
Documentation translated to md

### LINKED ISSUE #187: Translate whole roxygen documentation to md syntax

### PR DESCRIPTION
**Pull request by GegznaV**
PR should be carefully reviewed as most of the translations were automatic.

Closes #187.

### CODE REVIEW

**Comment by GegznaV** [comment]
The results in the last commit are displayed here: https://cbeleites.github.io/hyperSpec/reference/index.html

**Comment by GegznaV** [comment]
The documentation was translated to markdown. Then I did some review and manual corrections. Documentation needs a more thorough revision. But it is out of the scope of this PR.
I think PR can be accepted as it passes R CMD check ✔️ 
***
Note: `@ md` tag is not necessary anymore (see cd80674 for details). This information could be updated in CONTRIBUTING.md: I think these two points are not needed:
image

**Comment by GegznaV** [comment]
@cbeleites, @bryanhanson, @ximeg can I do anything (e.g., answer some questions) to make this branch merged sooner? I think I will have the access to the internet this evening (in 6-8 hours) and tomorrow in the morning (in ~ 12-16 hours). After that, I might not have proper access to the internet for several weeks.
The link above still displays the correct version of the website (except package version, which is displayed as `0.99`, and this is done on purpose).

**Comment by cbeleites** [comment]
I'll merge the branch now. 

I suspect that we'll need to correct some of the auto-translations (I think I spotted some links were topics became functions), e.g. Math -> Math().
But we can do that in smaller steps and let @GegznaV have his much earned holidays!

**Comment by cbeleites** [comment]
I also updated `CONTRIBUTING.md`

**Pull request merged**
