### PR TITLE
Release 0.100.0

### PR DESCRIPTION
**Pull request by GegznaV**
I suggest releasing the CRAN version of `hyperSpec` with:

1. updated and more regular version number format (`0.100`) so that it was easier for users, who are not ready for v1.0, to install the last non-1.0 version from CRAN. E.g., by using
 ```r
 remotes::install_version("hyperSpec", version = "0.100")
 ```
 2. updated URLs that point to the new GitHub repo (despite the fact that the user uses < 1.0 version of `hyperSpec`).
 
 
 What do you think @cbeleites and @bryanhanson?

### CODE REVIEW

**Comment by GegznaV** [comment]
I also think, that row, which starts with `@sed "s/\(^Version:` in the Make file, should also be modified in order not to use non-standard version format. Most probably, part `$(DATE)` should be removed. Unfortunately, I do not know Make so I cannot tell exactly.

On the other hand, the Make code might not work as the Structure on `Version` field in `DESCRIPTION` was changed manually (it does not contain a hyphen ( `-` ) anymore.

The full section of interest from the Make file:

```make
DESCRIPTION: $(shell find hyperSpec -maxdepth 1 -daystart -not -ctime 0 -name "DESCRIPTION") #only if not modified today
	@echo update DESCRIPTION
	@sed "s/\(^Version: .*-\)\(20\)\?[0-9][0-9][0-1][0-9][0-3][0-9]\(.*\)$$/\1$(DATE)\3/" hyperSpec/DESCRIPTION > .DESCRIPTION
	@sed "s/\(^Date: .*\)20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]\(.*\)$$/\1`date +%F`\2/" .DESCRIPTION > hyperSpec/DESCRIPTION
	@rm .DESCRIPTION
```

Can the whole section be commented out as we do not want to change the version number in `DESCRIPTION` anymore and the date can be updated manually?

**Comment by GegznaV** [comment]
**TASK:** 
- [ ] Export new names of renamed functions to make `hySpc.read.jdx` and `hySpc.read.spe` work if released on CRAN.

**Comment by cbeleites** [comment]
renamed functions I've found so far:

  - [ ] `hy_set_options`
  - [ ] `hy_get_option`
  - [ ] `read_txt_long`
  - [ ] `read_txt_wide`
  - [ ] ` .wl_fix_unit_name` 
  - [ ] `wl_convert_units`

**Comment by cbeleites** [comment]
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'Future-funcrions'
  ‘spc’ ‘filename’ ‘...’ ‘file.remove.emptyspc’ ‘file.keep.name’
  ‘tolerance’
```
- can you inherit the parameters?
- func*r*ions -> functions

**Comment by GegznaV** [comment]
@cbeleites, can you check for R CMD errors?

**Pull request merged**
