### PR TITLE
Fix/164 Update instructions in README

### LINKED ISSUE #164: Update README after merging #159 and/or #162
After PR #159 and/or #162 are merged into `develop` branch, the instructions in the `README` file should be updated appropriately.

### PR DESCRIPTION
**Pull request by GegznaV**
After PR #159 and/or #162 are merged, this PR suggests, how `README.md` file may look like.  Closes #164.  But firstly:

- [x] either PR #159 or #162, or both should be merged;
- [x] issue #163 should be addressed or discussed.

### CODE REVIEW

**Comment by GegznaV** [comment]
Here is a print screen of rendered README file I suggest:

image

**Comment by cbeleites** [comment]
Merging should be OK now that all other PRs are merged, right?

**Comment by GegznaV** [comment]
I'm testing now...

**Comment by GegznaV** [comment]
The results are that

image

```r
remotes::install_github("cbeleites/hyperSpec/hyperSpec", ref = "develop")
```
installs the package without documentation (see #163).

If that is OK, we can merge.

**Comment by cbeleites** [comment]
I'll merge now since the instructions we currently display are anyways much further off what is needed by now.

**Pull request merged**
