### PR TITLE
standardize/style code formatting

### PR DESCRIPTION
**Pull request by eoduniyi**
Used styler (i.e., style_dir("R/",...)) package to adhere to tidyverse default consistent code style.

### CODE REVIEW

**Comment by bryanhanson** [comment]
Did you build and check after styling? Always a good idea to ensure it all still works.

**Comment by eoduniyi** [comment]
Yes, and I remember a while back (sometime around when I first submitted the pull request #107) I tried to build after styling but ran into the same issue #111...just tried building again a few minutes ago and the same thing happened.

**Comment by eoduniyi** [comment]
[Erick's pull request on code styling](https://trello.com/c/ujpws442/25-ericks-pull-request-on-code-styling)

**Comment by bryanhanson** [comment]
I will review once #111 is resolved and I can B & C locally.

**Comment by eoduniyi** [comment]
> Looks good to me. I found a few files where spacing to align things was not recognized by `styler::style()`, but I think it's easier to take care of that after this monster-commit is merged.
> 
> The files/functions are:
> 
> * `pooled.cov()`
> * `makeraster()`
> * the generic `plot()`
> * read.spe.R

WOW, nice catch!

**Comment by GegznaV** [comment]
A few remarks:

> Since it was automatically generated, it's probably fine. (@ximeg)

The author of **styler** package Yihui Xie thinks, that after automatic corrections the code must be thoroughly checked (by unit test or manually). But as unit test did not fail, it should be OK.

> I think it's easier to take care of that after this monster-commit is merged. (@cbeleites)

I agree.

**Pull request merged**
