### PR TITLE
use git clean for Makefile target clean, remove target superclean.  

### LINKED ISSUE #104: `make clean` breaks the build process
There is a bug somewhere in the build system. After `make clean` is executed, `make` cannot build `hyperSpec`.

## How to reproduce
I have the very same version (commit 43e439db) and all dependencies installed.
```
git clone https://github.com/cbeleites/hyperSpec.git
cd hyperSpec/
make   # works
make   # works
make clean
make   # error
```

Error message:

```
rkiselev@pc158697:~/tmp/hyperSpec$ make
update DESCRIPTION
Roxygenize
Updating hyperSpec documentation
Writing NAMESPACE
Loading hyperSpec
Loading required package: lattice
Loading required package: grid
Loading required package: ggplot2
Error in FUN(X[[i]], ...) : empty (zero-byte) input file
Calls: document ... <Anonymous> -> load_data -> unlist -> lapply -> FUN
Execution halted
Makefile:67: recipe for target 'roxygenize' failed
make: *** [roxygenize] Error 1
```

To fix this, I run
```
git clean -xfd --exclude .Rhistory --exclude .Rproj.user/ --exclude hyperSpec.Rproj
make
```
Looks like `make clean` leaves some intermediate files in the dependency chain, and `make` gets confused.

### PR DESCRIPTION
**Pull request by cbeleites**
Fixes #104

### CODE REVIEW

**Comment by ximeg** [comment]
@cbeleites , now git clean is invoked when I call `make clean`, but unfortunately I still get the error message reported in #111 during building (both with `make` and `make bootstrap`).
```
Error in .local(.Object, ...) : object '.chondro.wl' not found
Calls: document ... .make.chondro -> new -> initialize -> initialize -> .local
Execution halted
make: *** [Makefile:68: roxygenize] Error 1
```

**Comment by bryanhanson** [comment]
I was not invoking `git lfs pull` so thanks for that reminder.  With your new changes issues #119 and #120 remain.

**Comment by cbeleites** [comment]
Since `git lfs` means that users *must* have `git` installed, does it make sense to call `git lfs pull` in the during `make bootstrap`?

**Comment by bryanhanson** [comment]
I think so.

I think installing git lfs is an additional step too (IIRC), so maybe those steps should go in the README (I see you updated README but I have not had a chance to look yet).

**Comment by cbeleites** [comment]
No, I did not change the README in that respect. But it already says that `git lfs` must be installed.

**Pull request merged**
