### PR TITLE
standardize/style code formatting

### PR DESCRIPTION
**Pull request by eoduniyi**
Used styler (i.e., style_dir("R/",...)) package to adhere to tidyverse default consistent code style.

### CODE REVIEW

**Comment by cbeleites** [comment]
Many thanks, you passed the test :+1: 

I will not yet merge your changes into **hyperSpec**, though: your pull request is comprehensive and thus nothing would be left for other applicants.

**Comment by ximeg** [comment]
[Pull requests](https://trello.com/c/bGRks3Xv/1-pull-requests)

**Comment by ximeg** [comment]
[Erick's PR - code formatting](https://trello.com/c/ZunhSIkr/18-ericks-pr-code-formatting)

**Comment by eoduniyi** [comment]
[Erick's pull request on code styling](https://trello.com/c/ujpws442/25-ericks-pull-request-on-code-styling)

**Pull request closed without merging**
