### PR TITLE
Fix unused functions from Collate: in DESCRIPTION

### LINKED ISSUE #278: Remove internal not used factor2num()
There is a non-exported and not used function `factor2num()`. Shouldn't it be removed from **hyperSpec**? What do you think @cbeleites?

### LINKED ISSUE #279: Remove internal not used .call.list()
There is a non-exported and not used function `.call.list()`. Shouldn't it be removed from **hyperSpec**? What do you think @cbeleites?

### LINKED ISSUE #280: Remove internal not used .split.dots
There is a non-exported and not used function `.split.dots()`. Shouldn't it be removed from **hyperSpec**? What do you think @cbeleites?

### PR DESCRIPTION
**Pull request by sangttruong**
.factor2num() turns out to be a non-exported function.
Thus, removing it is necessary to reduce complexity.

Resolve #278, Resolve #279, Resolve #280

### CODE REVIEW

**Comment by bryanhanson** [comment]
Looks like `call_list.R` needs to be removed from the `Collate:` field in `DESCRIPTION`.

**Review by bryanhanson — COMMENTED** [review]
@sangttruong we've found the best practice is to make the commit messages short but specific.  For this particular change I would have used something like "remove  unused functions from Collate: in DESCRIPTION" since the actual removal of the function files was in the prev. commit.  This really helps when there are a lot of us working on the project.

**Review by GegznaV — CHANGES_REQUESTED** [review]
@sangttruong, the "magical words" must be in the first message of the pull request otherwise the issues will not be properly linked to this PR. Please, edit the message.

**Comment by GegznaV** [comment]
Why do you want to close this PR?

**Review by GegznaV — CHANGES_REQUESTED** [review]
OK, the previous remark was addressed.

Still in the package, there are places, where the names of the removed files are mentioned in `@include` statements. Please remove the statements. 
Run tests and check the package locally and make sure that the tests pass and there are no check-up errors locally before pushing changes (commits) to GitHub.

**Comment by sangttruong** [comment]
Delete fork

**Comment by GegznaV** [comment]
This PR was closed in favor of #317.

**Pull request closed without merging**
