### PR TITLE
Feature/145 chondro replace

### LINKED ISSUE #145: Replace `chondro` in the examples with fauxCell

### PR DESCRIPTION
**Pull request by eoduniyi**
`chondro` has been replaced with `fauxCell` in all the .R files (examples; unit test) that reference `chondro`

**Note:** vignettes still makes use of `chondro`

Closes #145

### CODE REVIEW

**Comment by eoduniyi** [comment]
> @eoduniyi When I try to check this branch I get a message that `flu` is not exported. Strangely, I don't think you touched `flu.R` but it does not have an `@export` statement. Since you can build/check/install perhaps this is a problem with my local files.

Yo u are correct, I did not touch `flu.R`. Strange, when I `make->build->check` I get no such messages.

**Comment by GegznaV** [comment]
Usually, the documentation of dataset should not have `@export` roxygen tag. In http://r-pkgs.had.co.nz/data.html#documenting-data it is said:

> Never `@export` a data set.

**Comment by GegznaV** [comment]
@eoduniyi, in https://github.com/r-hyperspec/hySpc.dplyr/issues/23#issuecomment-643642520, I wrote about the "magical" words (fix, fixes, close, closes, resolve, resolves) that make PR to close an issue. These words work only in the main message of PR. So I updated your the main PR (pull request) message with:
image

**Comment by GegznaV** [comment]
I can confirm, that word `chondro` is missing in the most of `*.R` files in this project, except:

- ✔️  `chondro.R`: it is expected to be there 
- ❕ `fauxCell.R`: I'm not sure if the new users know what `chondro` dataset is and, in my opinion, it would be sufficient to mention that this is an artificial dataset that imitates 2D Ramman scattering spectra.
- ✔️ `read.txt.Reinshaw.R`: the raw data of `chondro` dataset is used for unit testing. Will be solved after file IO functions are moved to a separate package.
- ✔️ `spc.fit.poly.R`: there is some commented code, that mentions `chondro` .



image

**Pull request merged**
